apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress-class: traefik
  name: todo-app-list
spec:
  rules:
  - host: workshop.nvrbkdown.uz
    http:
      paths:
      - backend:
          service:
            name: todo-list-app
            port:
              number: 80
        path: /
        pathType: Prefix


helm upgrade --install mon \
--values vm-operator/values-k8s-stack.yaml \
--debug \
-n monitoring \
--create-namespace \
--version $VMCHART \
vm/victoria-metrics-k8s-stack \
--set vmsingle.spec.image.tag=$VM \
--set vmalert.spec.image.tag=$VM \
--set vmagent.spec.image.tag=$VM \
--set alertmanager.spec.image.tag=$ALERTMANAGER \
--set "alertmanager.config.receivers[0].webhook_configs[0].url=$ONCALL_INTERGRATION_URL" \
--set grafana.image.tag=$GRAFANA \
--set vmagent.spec.externalLabels.cluster=$CLUSTER_NAME \
--set "vmsingle.ingress.hosts[0]=vm.$DOMAIN" \
--set "vmsingle.ingress.tls[0].hosts[0]=vm.$DOMAIN" \
--set "alertmanager.ingress.hosts[0]=alert.$DOMAIN" \
--set "alertmanager.ingress.tls[0].hosts[0]=alert.$DOMAIN" \
--set "grafana.ingress.hosts[0]=mon.$DOMAIN" \
--set "grafana.ingress.tls[0].hosts[0]=mon.$DOMAIN"
